### ISSUE TITLE
Implement additional metadata tag for approved uploads to PAW

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datapackr-app#2]
PAW users need additional information on possible discrepancies between what is displayed in PAW and DATIM.  The app should include a tag to indicate that any data coming from the app itself (uploaded to PAW via self-service) is tagged as being "Not approved". 

When a member of the DATIM systems team uploads a file to DATIM, this file should also overwrite any data which is currently in the PAW S3 bucket AND it should be marked as being "Approved". 

@arcann @jacksonsj  does this sound about right?

**Comment by arcann** [comment]
Yes that will meet our needs. We'll use the versioning on the S3 files to see the history of uploads and approval_status tag values.

**Comment by arcann** [comment]
iHub work for this is in https://jira.pepfar.net/browse/DMA-1421

**Comment by arcann** [comment]
Also relates to https://jira.pepfar.net/browse/APD-626

**Comment by jason-p-pickering** [comment]
This has been implemented in 7bb847cdff49f2b378c612c497d00b28dedeef91.
