### ISSUE TITLE
Generate flatpack without requiring for PSNUbyIM tab

### ISSUE THREAD

**Issue by abeagedew** [pepfar-datim/datapackr-app#3]
Is it possible to generate the flatpack via the self-service app with requiring for the PSNUbyIM tab to be generated at first?

**Comment by jason-p-pickering** [comment]
@abeagedew it should be possible to generate the FlatPack without a PSNUxIM tab now. However, only the "Indiacator" summary tab will be available, as this is generated from the main Excel tabs (not the PSNUxIM tab).

**Comment by abeagedew** [comment]
Thanks @jason-p-pickering , this has been resolved. We had this issue at the beginning of COP.
